"use strict";
const PROFILE_KEY='darts-cricket-profiles-v1',HISTORY_KEY='darts-cricket-history-v1',ACTIVE_KEY='darts-cricket-active-v1',THEME_KEY='darts-trainer-theme';
const TARGETS=['20','19','18','17','16','15','Bull'],VALUES={20:20,19:19,18:18,17:17,16:16,15:15,Bull:25};
const LEVELS=[['rookie','Anfänger',.30],['casual','Leicht',.43],['normal','Mittel',.57],['strong','Schwer',.72],['expert','Profi',.86]];
const $=id=>document.getElementById(id), clone=x=>JSON.parse(JSON.stringify(x)), uid=p=>`${p}-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let profiles=load(PROFILE_KEY,[]),history=load(HISTORY_KEY,[]),lineup=[],game=null,mult=1,botTimer=null;
function theme(){document.body.classList.toggle('dark',localStorage.getItem(THEME_KEY)==='dark')} theme(); $('themeToggle').onclick=()=>{localStorage.setItem(THEME_KEY,document.body.classList.contains('dark')?'light':'dark');theme()};
function levelInfo(k){return LEVELS.find(x=>x[0]===k)||LEVELS[2]}
function participantProfile(p){return {id:uid('seat'),profileId:p.id,name:p.name,type:'human'}}
function bot(k){const l=levelInfo(k);return{id:uid('bot'),name:`Bot ${l[1]}`,type:'bot',level:k}}
function renderSetup(){
 $('lineupCount').textContent=lineup.length;$('startBtn').disabled=lineup.length<2;
 $('lineup').className=lineup.length?'lineup':'lineup empty';$('lineup').innerHTML=lineup.length?lineup.map((p,i)=>`<div class="lineup-row"><span><strong>${i+1}. ${p.name}</strong><br><small class="muted">${p.type==='bot'?levelInfo(p.level)[1]:'Mensch'}</small></span><button class="mini" data-remove="${p.id}">×</button></div>`).join(''):'Noch niemand im Spiel.';
 $('profiles').innerHTML=profiles.map(p=>`<div class="profile-row"><strong>${p.name}</strong><span><button class="mini" data-add="${p.id}">+</button><button class="mini" data-del="${p.id}">×</button></span></div>`).join('');
 const opts=profiles.map(p=>`<option value="${p.id}">${p.name}</option>`).join(''); const a=$('compareA').value,b=$('compareB').value;$('compareA').innerHTML='<option value="">Spieler A</option>'+opts;$('compareB').innerHTML='<option value="">Spieler B</option>'+opts;if(profiles.some(p=>p.id===a))$('compareA').value=a;if(profiles.some(p=>p.id===b))$('compareB').value=b; renderCompare(); renderHistory();
}
$('profileForm').onsubmit=e=>{e.preventDefault();let n=$('profileName').value.trim();if(!n||profiles.some(p=>p.name.toLowerCase()===n.toLowerCase()))return;let p={id:uid('human'),name:n};profiles.push(p);save(PROFILE_KEY,profiles);lineup.push(participantProfile(p));$('profileName').value='';renderSetup()};
$('profiles').onclick=e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.add){let p=profiles.find(x=>x.id===b.dataset.add);if(p&&!lineup.some(x=>x.profileId===p.id))lineup.push(participantProfile(p))}if(b.dataset.del){let p=profiles.find(x=>x.id===b.dataset.del);if(p&&confirm(`${p.name} löschen?`)){profiles=profiles.filter(x=>x.id!==p.id);lineup=lineup.filter(x=>x.profileId!==p.id);save(PROFILE_KEY,profiles)}}renderSetup()};
$('lineup').onclick=e=>{let b=e.target.closest('[data-remove]');if(b){lineup=lineup.filter(x=>x.id!==b.dataset.remove);renderSetup()}};
$('addBotBtn').onclick=()=>{lineup.push(bot($('botLevel').value));renderSetup()};
$('addAllBotsBtn').onclick=()=>{LEVELS.forEach(l=>lineup.push(bot(l[0])));renderSetup()};
function newGame(){return{id:uid('game'),startedAt:Date.now(),players:lineup.map(p=>({...clone(p),score:0,marks:Object.fromEntries(TARGETS.map(t=>[t,0])),placement:null,darts:0,marksTotal:0})),current:0,dartsTurn:[],placements:[],round:1,undo:[],finished:false}}
function active(p){return !p.placement} function activeIds(){return game.players.map((p,i)=>active(p)?i:-1).filter(i=>i>=0)} function closed(p){return TARGETS.every(t=>p.marks[t]>=3)}
function winnerIndex(){let ids=activeIds();return ids.find(i=>closed(game.players[i])&&ids.every(j=>game.players[i].score>=game.players[j].score))??-1}
function assign(i){let p=game.players[i];if(p.placement)return;p.placement=game.placements.length+1;game.placements.push(i)}
function cascadePlacements(first){assign(first);let auto=[];while(activeIds().length>1){let n=winnerIndex();if(n<0)break;assign(n);auto.push(n)}let ids=activeIds();if(ids.length===1){assign(ids[0]);finishGame();return{auto,last:ids[0],finished:true}}save(ACTIVE_KEY,game);return{auto,last:null,finished:false}}
function finishGame(){game.finished=true;let rec={id:game.id,startedAt:game.startedAt,finishedAt:Date.now(),rounds:game.round,winnerName:game.players.find(p=>p.placement===1)?.name,players:game.players.map(p=>({profileId:p.profileId||null,name:p.name,type:p.type,level:p.level||null,score:p.score,placement:p.placement,dartsThrown:p.darts,marksTotal:p.marksTotal,marks:p.marks}))};history.push(rec);save(HISTORY_KEY,history);localStorage.removeItem(ACTIVE_KEY);renderHistory()}
function openPlacement(first,res){let p=game.players[first];$('placeBadge').textContent=`PLATZ ${p.placement}`;$('placeTitle').textContent=`${p.name} wird ${p.placement}.`;let txt=res.auto.map(i=>`${game.players[i].name} wird ebenfalls sofort ${game.players[i].placement}.`).join(' ');if(res.last!==null)txt+=` ${game.players[res.last].name} belegt automatisch Platz ${game.players[res.last].placement}.`;$('placeSummary').textContent=txt||'Die übrigen Spieler spielen weiter.';$('placeRanking').innerHTML=[...game.players].sort((a,b)=>(a.placement||99)-(b.placement||99)).map(x=>`<div class="rank-row"><span>${x.placement?x.placement+'.':'…'} ${x.name}</span><strong>${x.score}</strong></div>`).join('');$('continueBtn').hidden=res.finished;$('placeDialog').showModal()}
function applyDart(i,target,m){let p=game.players[i];p.darts++;if(!target)return;let raw=target==='Bull'?Math.min(2,m):m;p.marksTotal+=raw;let before=p.marks[target],close=Math.min(raw,3-before),extra=raw-close;p.marks[target]=Math.min(3,before+raw);if(extra>0&&game.players.some((o,j)=>j!==i&&active(o)&&o.marks[target]<3))p.score+=extra*VALUES[target]}
function record(target){if(!game||game.finished||!active(game.players[game.current])||game.dartsTurn.length>=3)return;game.undo.push(clone(game));let i=game.current;applyDart(i,target,target?mult:0);game.dartsTurn.push({target,mult:target?mult:0});mult=1;let w=winnerIndex();if(w>=0){let res=cascadePlacements(w);renderGame();openPlacement(w,res);return}if(game.dartsTurn.length===3)advance();else{save(ACTIVE_KEY,game);renderGame()}}
function nextActive(from){for(let o=1;o<=game.players.length;o++){let i=(from+o)%game.players.length;if(active(game.players[i]))return i}return-1}
function advance(){let prev=game.current,n=nextActive(prev);if(n<0)return;if(n<=prev)game.round++;game.current=n;game.dartsTurn=[];save(ACTIVE_KEY,game);renderGame();scheduleBot()}
function renderGame(){let p=game.players[game.current];$('currentPlayerName').textContent=p.name;$('dartCounter').textContent=`${game.dartsTurn.length}/3`;$('turnInfo').textContent=`Runde ${game.round} · ${p.name}`;document.querySelectorAll('[data-mult]').forEach(b=>b.classList.toggle('selected',+b.dataset.mult===mult));
 let heads=game.players.map((x,i)=>`<div class="cell head ${i===game.current&&!x.placement?'active':''} ${x.placement?'placed':''}">${x.placement?x.placement+'. ':''}${x.name}<div class="score">${x.score}</div><small>${x.darts} Darts</small></div>`).join('');let rows=TARGETS.map(t=>`<div class="cell head">${t}</div>`+game.players.map(x=>`<div class="cell mark ${x.placement?'placed':''}">${x.marks[t]>=3?'○':x.marks[t]===2?'✕':x.marks[t]===1?'╱':''}</div>`).join('')).join('');$('scoreboard').innerHTML=`<div class="score-grid" style="--players:${game.players.length}"><div class="cell head">Ziel</div>${heads}${rows}</div>`;
 $('targetButtons').innerHTML=TARGETS.map(t=>`<button data-target="${t}">${t}</button>`).join('')+'<button class="miss" data-target="Miss">Miss</button>';document.querySelector('.throw-card').style.display=p.type==='bot'?'none':'block';}
function scheduleBot(){clearTimeout(botTimer);if(!game||game.finished||game.players[game.current].type!=='bot')return;botTimer=setTimeout(botTurn,180)}
function botTurn(){if(!game||game.finished)return;let i=game.current,p=game.players[i],acc=levelInfo(p.level)[2];for(let d=0;d<3;d++){if(game.finished||game.current!==i)break;let opens=TARGETS.filter(t=>p.marks[t]<3),target=opens[0]||TARGETS.find(t=>game.players.some((o,j)=>j!==i&&active(o)&&o.marks[t]<3))||'20';let m=Math.random()<acc?(Math.random()<.25?3:Math.random()<.35?2:1):0;applyDart(i,m?target:null,m);game.dartsTurn.push({target:m?target:null,mult:m});let w=winnerIndex();if(w>=0){let res=cascadePlacements(w);renderGame();openPlacement(w,res);return}}advance()}
$('targetButtons').onclick=e=>{let b=e.target.closest('[data-target]');if(b)record(b.dataset.target==='Miss'?null:b.dataset.target)};document.querySelector('.mult-grid').onclick=e=>{let b=e.target.closest('[data-mult]');if(b){mult=+b.dataset.mult;renderGame()}};
$('undoBtn').onclick=()=>{if(!game?.undo?.length)return;game=game.undo.pop();save(ACTIVE_KEY,game);renderGame()};$('backBtn').onclick=()=>{if(game&&!game.finished)save(ACTIVE_KEY,game);$('gameView').hidden=true;$('setupView').hidden=false;renderSetup()};$('resetBtn').onclick=()=>{if(confirm('Spiel neu starten?')){game=newGame();save(ACTIVE_KEY,game);renderGame();scheduleBot()}};
$('startBtn').onclick=()=>{game=newGame();save(ACTIVE_KEY,game);$('setupView').hidden=true;$('gameView').hidden=false;renderGame();scheduleBot()};$('continueBtn').onclick=()=>{$('placeDialog').close();if(!game.finished){advance()}};$('newGameBtn').onclick=()=>{$('placeDialog').close();game=null;localStorage.removeItem(ACTIVE_KEY);$('gameView').hidden=true;$('setupView').hidden=false;renderSetup()};
function renderHistory(){if(!history.length){$('history').className='empty';$('history').textContent='Noch kein Spiel abgeschlossen.';return}$('history').className='';$('history').innerHTML=[...history].reverse().slice(0,15).map(h=>`<div class="history-row"><span><strong>${h.winnerName}</strong> gewinnt<br><small class="muted">${new Date(h.finishedAt).toLocaleString('de-AT')}</small></span><span>${h.players.sort((a,b)=>a.placement-b.placement).map(p=>`${p.placement}. ${p.name}`).join(' · ')}</span></div>`).join('')}
function renderCompare(){let a=$('compareA').value,b=$('compareB').value;if(!a||!b||a===b){$('comparison').className='empty';$('comparison').textContent='Wähle zwei unterschiedliche Spieler.';return}let pa=profiles.find(p=>p.id===a),pb=profiles.find(p=>p.id===b);let games=history.map(h=>({h,a:h.players.find(p=>p.profileId===a),b:h.players.find(p=>p.profileId===b)})).filter(x=>x.a&&x.b);let aw=games.filter(x=>x.a.placement<x.b.placement).length,bw=games.filter(x=>x.b.placement<x.a.placement).length,ap=games.length?games.reduce((s,x)=>s+x.a.placement,0)/games.length:0,bp=games.length?games.reduce((s,x)=>s+x.b.placement,0)/games.length:0;let am=games.reduce((s,x)=>s+(x.a.marksTotal||0),0),ad=games.reduce((s,x)=>s+(x.a.dartsThrown||0),0),bm=games.reduce((s,x)=>s+(x.b.marksTotal||0),0),bd=games.reduce((s,x)=>s+(x.b.dartsThrown||0),0);$('comparison').className='compare-grid';$('comparison').innerHTML=`<div><span>Gemeinsame Spiele</span><strong>${games.length}</strong></div><div><span>${pa.name} davor</span><strong>${aw}</strong></div><div><span>${pb.name} davor</span><strong>${bw}</strong></div><div><span>Head-to-Head</span><strong>${aw}:${bw}</strong></div><div><span>Ø Platz ${pa.name}</span><strong>${games.length?ap.toFixed(2):'–'}</strong></div><div><span>Ø Platz ${pb.name}</span><strong>${games.length?bp.toFixed(2):'–'}</strong></div><div><span>MPR ${pa.name}</span><strong>${ad?((am/ad)*3).toFixed(2):'–'}</strong></div><div><span>MPR ${pb.name}</span><strong>${bd?((bm/bd)*3).toFixed(2):'–'}</strong></div>`}
$('compareA').onchange=renderCompare;$('compareB').onchange=renderCompare;$('clearHistoryBtn').onclick=()=>{if(history.length&&confirm('History löschen?')){history=[];save(HISTORY_KEY,history);renderSetup()}};
let activeGame=load(ACTIVE_KEY,null);if(activeGame&&!activeGame.finished){game=activeGame;$('setupView').hidden=true;$('gameView').hidden=false;renderGame();scheduleBot()}else renderSetup();
